version: '3.8'

services:

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: model-tech-demo-frontend
    environment:
      VITE_API_URL: https://api.staging.model-technologie.com/api
    networks:
      - dokploy-network
    restart: unless-stopped

networks:
  dokploy-network:
    name: dokploy-network
    external: true
