version: '3.8'

services:

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: model-tech-demo-frontend
    environment:
      VITE_API_URL: https://api.model-technologie.com/api
    ports:
      - "5000:5000"
    networks:
      - dokploy-network
    restart: unless-stopped

networks:
  dokploy-network:
    external: true
